# This file will be commited into git. 
# Please do not save credentials in this file. 

[build]

	base = ""
	publish = "public/"
	command = "yarn build"

	[build.environment]

		SPACE_ID = "PLACEHOLDER_SPACE_ID"

[context.production]

	[context.production.environment]

		ACCESS_TOKEN = "PLACEHOLDER_ACCESS_TOKEN"
		GATSBY_PREVIEW = "false"
		CONTENTFUL_HOST = "cdn.contentful.com"

[context.stage]

	[context.stage.environment]

		ACCESS_TOKEN = "PLACEHOLDER_PREVIEW_TOKEN"
		GATSBY_PREVIEW = "true"
		CONTENTFUL_HOST = "preview.contentful.com"

[context.develop]

	[context.develop.environment]

		ACCESS_TOKEN = "PLACEHOLDER_PREVIEW_TOKEN"
		GATSBY_PREVIEW = "true"
		CONTENTFUL_HOST = "preview.contentful.com"