// flow-typed signature: a958da135f9f9b609a08dce3f7d575da
// flow-typed version: <<STUB>>/rebass_v3.0.0-9/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rebass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rebass' {
  declare module.exports: {
    Flex: any,
    Box: any,
    Image: any,
    Card: any,
    Button: any,
    Heading: any,
    Text: any,
    Link: any,
  }
}
