import React from 'react'
import { Card, Heading, Code, Text } from 'rebass'

import Layout from '../components/Layout'

export default class Page extends React.Component {
  render() {
    return (
      <Layout>
        <Heading mb={2}>Hello World.</Heading>
        <Text>
          You are looking at index generated by src/pages/index.js.
          <br />
          By default, this page does not query anything from Contentful.
          <br />
          You can still load CMS content by
          <Card my={3}>
            <Code>{"import {QueryStatic} from 'gatsby'"}</Code>
          </Card>
          Please check Gatsby documentation for more information.
        </Text>
      </Layout>
    )
  }
}
