import React from 'react';
import { Box, Card, Heading, Text } from 'rebass';

import Layout from '../components/Layout';

export default () => (
  <Layout>
    <Heading mb={2}>Hello World.</Heading>
    <Text>
      You are looking at index generated by src/pages/index.js.
      <br />
      By default, this page does not query anything from Contentful.
      <br />
      You can still load CMS content by
      <Card my={3}>
        <Box>{"import {QueryStatic} from 'gatsby'"}</Box>
      </Card>
      Please check Gatsby documentation for more information.
    </Text>
  </Layout>
);
